export const userRole = ["INDIVIDUAL_USER",  "CHARITABLE_ORGANIZATION","CHARITY_SHOP","ECO_FRIENDLY_STORE","CELEBRITY","AMBASSADOR","PROFESSIONAL_SELLER","ASSISTED_SELLER"]

export const role = {
    INDIVIDUAL_USER: "INDIVIDUAL_USER",
    CHARITABLE_ORGANIZATION: "CHARITABLE_ORGANIZATION",
    CHARITY_SHOP: "CHARITY_SHOP",
    ECO_FRIENDLY_STORE: "ECO_FRIENDLY_STORE",
    CELEBRITY: "CELEBRITY",
    AMBASSADOR: "AMBASSADOR",
    PROFESSIONAL_SELLER: "PROFESSIONAL_SELLER",
    ASSISTED_SELLER: "ASSISTED_SELLER"
}