export const productData = [
  {
    name: "Teens Top & Pant",
    image: "/offer_page_product3.png",
    price: 25,
    quantity: 2,
    color: "Brown",
    size: "XLL",
    donation: "10%",
    shipping_fees: "30.00",
    features: ["Authentication of Goods", "Buyer Protection"],
  },
  {
    name: "Teens Top & Pant",
    image: "/offer_page_product3.png",
    price: 24,
    quantity: 3,
    color: "Brown",
    size: "XLL",
    donation: "10%",
    shipping_fees: "30.00",
    features: ["Authentication of Goods", "Buyer Protection"],
  },
  {
    name: "Teens Top & Pant",
    image: "/offer_page_product3.png",
    price: 24,
    quantity: 3,
    color: "Brown",
    size: "XLL",
    donation: "10%",
    shipping_fees: "30.00",
    features: ["Authentication of Goods", "Buyer Protection"],
  },
];
