export const GENERAL_BADGES = [
  {
    id: "fashion-philanthropist",
    title: "Fashion Philanthropist",
    description:
      "Recognizes users who have raised or donated over £1,000 through sales or charity contributions — true icons of giving back through fashion.",
    icon: "💷",
    category: "general" as const,
    subtitle: "£0 - £1,000",
  },
  {
    id: "style-starter",
    title: "Style Starter",
    description: "List first 2 items",
    icon: "👔",
    category: "general" as const,
    progress: { current: 0, total: 2 },
  },

  {
    id: "first-purchase",
    title: "First Purchase",
    description: "Buy pre-loved piece",
    icon: "🛍️",
    category: "general" as const,
    progress: { current: 0, total: 1 },
  },
  {
    id: "money-donor",
    title: "Money Donor",
    description: "Donate to charity",
    icon: "❤️",
    category: "general" as const,
    progress: { current: 0, total: 1 },
  },
  {
    id: "eco-hero",
    title: "Eco Hero",
    description: "All three donations",
    icon: "🌍",
    category: "general" as const,
    progress: { current: 0, total: 3 },
  },
  {
    id: "first-sale",
    title: "First Sale",
    description: "Complete first sale",
    icon: "✓",
    category: "general" as const,
    progress: { current: 0, total: 1 },
  },
  {
    id: "tree-planter",
    title: "Tree Planter",
    description: "Plant a tree",
    icon: "🌱",
    category: "general" as const,
    progress: { current: 0, total: 1 },
  },
  {
    id: "clothing-donor",
    title: "Clothing Donor",
    description: "Donate clothes",
    icon: "👕",
    category: "general" as const,
    progress: { current: 0, total: 1 },
  },
  {
    id: "frequent-seller",
    title: "Frequent Seller",
    description: "Consistent sales",
    icon: "🎁",
    category: "general" as const,
    progress: { current: 0, total: 50 },
  },
  {
    id: "top-buyer",
    title: "Top Buyer",
    description: "20+ purchases",
    icon: "⭐",
    category: "general" as const,
    progress: { current: 5, total: 20 },
  },
  {
    id: "speedy-shipper",
    title: "Speedy Shipper",
    description: "Ship within 24 hours",
    icon: "🚗",
    category: "general" as const,
    progress: { current: 0, total: 1 },
  },
  {
    id: "fashion-activist",
    title: "Fashion Activist",
    description: "10+ badges earned",
    icon: "🎖️",
    category: "general" as const,
    progress: { current: 3, total: 10 },
  },
];

export const ECO_BADGES = [
  {
    id: "sustainable-materials",
    title: "Sustainable Materials",
    description: "Use eco-friendly fabrics",
    icon: "🍃",
    category: "eco" as const,
    progress: { current: 0, total: 2 },
  },
  {
    id: "fast-shipper-eco",
    title: "Fast Shipper",
    description: "5+ orders in 24-48h",
    icon: "🚚",
    category: "eco" as const,
    progress: { current: 0, total: 5 },
  },
  {
    id: "top-eco-seller",
    title: "Top Eco Seller",
    description: "100+ eco items sold",
    icon: "🏆",
    category: "eco" as const,
    progress: { current: 45, total: 100 },
  },
  {
    id: "buyers-favourite-eco",
    title: "Buyers' Favourite",
    description: "100+ likes/favorites",
    icon: "💚",
    category: "eco" as const,
    progress: { current: 85, total: 100 },
  },
  {
    id: "trusted-seller",
    title: "Trusted Seller",
    description: "4.8★ rating, 10+ orders",
    icon: "✅",
    category: "eco" as const,
    progress: { current: 8, total: 10 },
  },
];

export const CHARITY_BADGES = [
  {
    id: "fast-shipper-charity",
    title: "Fast Shipper",
    description: "5+ charity orders fast",
    icon: "🚚",
    category: "charity" as const,
    progress: { current: 2, total: 5 },
  },
  {
    id: "buyers-favourite-charity",
    title: "Buyers' Favourite",
    description: "100+ likes, 4.8★ rating",
    icon: "💚",
    category: "charity" as const,
    progress: { current: 60, total: 100 },
  },
  {
    id: "top-charity-seller",
    title: "Top Charity Seller",
    description: "100+ items sold",
    icon: "🏆",
    category: "charity" as const,
    progress: { current: 75, total: 100 },
  },
  {
    id: "raised-1000",
    title: "Raised £1,000+",
    description: "Charity fundraising",
    icon: "💷",
    category: "charity" as const,
    progress: { current: 650, total: 1000 },
  },
  {
    id: "vintage-collection",
    title: "Vintage Collection",
    description: "10+ vintage items",
    icon: "👜",
    category: "charity" as const,
    progress: { current: 7, total: 10 },
  },
];
