export const blogsData = [
  {
    _id: 1,
    image: "/blogImage1.png",
    date: "Aug 12, 2024",
    totalFeedback: 12,
    description:
      "In a world where fast fashion is the norm, the concept of eco-friendly fashion is not just a trend—it’s a movement. At FASHI-ON, we believe that style should never come at the expense of the planet. That’s why our Eco-Friendly Stores are leading the way in redefining what it means to shop responsibly while still keeping your wardrobe fresh and stylish.",
  },
  {
    _id: 2,
    image: "/blogImage2.png",
    date: "Aug 12, 2024",
    totalFeedback: 12,
    description:
      "In a world where fast fashion is the norm, the concept of eco-friendly fashion is not just a trend—it’s a movement. At FASHI-ON, we believe that style should never come at the expense of the planet. That’s why our Eco-Friendly Stores are leading the way in redefining what it means to shop responsibly while still keeping your wardrobe fresh and stylish.",
  },
  {
    _id: 4,
    image: "/blogImage4.png",
    date: "Aug 12, 2024",
    totalFeedback: 12,
    description:
      "In a world where fast fashion is the norm, the concept of eco-friendly fashion is not just a trend—it’s a movement. At FASHI-ON, we believe that style should never come at the expense of the planet. That’s why our Eco-Friendly Stores are leading the way in redefining what it means to shop responsibly while still keeping your wardrobe fresh and stylish.",
  },
  {
    _id: 5,
    image: "/blogImage5.png",
    date: "Aug 12, 2024",
    totalFeedback: 12,
    description:
      "In a world where fast fashion is the norm, the concept of eco-friendly fashion is not just a trend—it’s a movement. At FASHI-ON, we believe that style should never come at the expense of the planet. That’s why our Eco-Friendly Stores are leading the way in redefining what it means to shop responsibly while still keeping your wardrobe fresh and stylish.",
  },
  {
    _id: 6,
    image: "/blogImage6.png",
    date: "Aug 12, 2024",
    totalFeedback: 12,
    description:
      "In a world where fast fashion is the norm, the concept of eco-friendly fashion is not just a trend—it’s a movement. At FASHI-ON, we believe that style should never come at the expense of the planet. That’s why our Eco-Friendly Stores are leading the way in redefining what it means to shop responsibly while still keeping your wardrobe fresh and stylish.",
  },
  {
    _id: 7,
    image: "/blogImage1.png",
    date: "Aug 12, 2024",
    totalFeedback: 12,
    description:
      "In a world where fast fashion is the norm, the concept of eco-friendly fashion is not just a trend—it’s a movement. At FASHI-ON, we believe that style should never come at the expense of the planet. That’s why our Eco-Friendly Stores are leading the way in redefining what it means to shop responsibly while still keeping your wardrobe fresh and stylish.",
  },
  {
    _id: 8,
    image: "/blogImage2.png",
    date: "Aug 12, 2024",
    totalFeedback: 12,
    description:
      "In a world where fast fashion is the norm, the concept of eco-friendly fashion is not just a trend—it’s a movement. At FASHI-ON, we believe that style should never come at the expense of the planet. That’s why our Eco-Friendly Stores are leading the way in redefining what it means to shop responsibly while still keeping your wardrobe fresh and stylish.",
  },
  {
    _id: 9,
    image: "/blogImage3.png",
    date: "Aug 12, 2024",
    totalFeedback: 12,
    description:
      "In a world where fast fashion is the norm, the concept of eco-friendly fashion is not just a trend—it’s a movement. At FASHI-ON, we believe that style should never come at the expense of the planet. That’s why our Eco-Friendly Stores are leading the way in redefining what it means to shop responsibly while still keeping your wardrobe fresh and stylish.",
  },
  {
    _id: 10,
    image: "/blogImage4.png",
    date: "Aug 12, 2024",
    totalFeedback: 12,
    description:
      "In a world where fast fashion is the norm, the concept of eco-friendly fashion is not just a trend—it’s a movement. At FASHI-ON, we believe that style should never come at the expense of the planet. That’s why our Eco-Friendly Stores are leading the way in redefining what it means to shop responsibly while still keeping your wardrobe fresh and stylish.",
  },
  {
    _id: 11,
    image: "/blogImage5.png",
    date: "Aug 12, 2024",
    totalFeedback: 12,
    description:
      "In a world where fast fashion is the norm, the concept of eco-friendly fashion is not just a trend—it’s a movement. At FASHI-ON, we believe that style should never come at the expense of the planet. That’s why our Eco-Friendly Stores are leading the way in redefining what it means to shop responsibly while still keeping your wardrobe fresh and stylish.",
  },
  {
    _id: 12,
    image: "/blogImage6.png",
    date: "Aug 12, 2024",
    totalFeedback: 12,
    description:
      "In a world where fast fashion is the norm, the concept of eco-friendly fashion is not just a trend—it’s a movement. At FASHI-ON, we believe that style should never come at the expense of the planet. That’s why our Eco-Friendly Stores are leading the way in redefining what it means to shop responsibly while still keeping your wardrobe fresh and stylish.",
  },
];

export const blogsFeedbacks = [
  {
    _id: 1,
    image: "/user.png",
    name: "Amanda P.",
    createAt: "2025-03-12T13:52:10.362Z",
    comment:
      "The service was both professional and affordable, exceeding my expectations. Right from the start, the contractor was transparent about the process, ensuring clarity in every step. They took the time to explain the issue in detail before beginning the work, making me feel confident in their expertise. Not only did they provide a clear breakdown of the repairs needed, but they also discussed potential solutions and costs upfront. There were no hidden fees or surprises, which I truly appreciated. Throughout the job, they maintained excellent communication, keeping me informed of the progress.The work was completed efficiently, with great attention to detail and professionalism. I highly recommend their services for anyone looking for reliable and transparent home repairs!",
  },
  {
    _id: 2,
    image: "/user.png",
    name: "Amanda P.",
    createAt: "2025-03-12T13:52:10.362Z",
    comment:
      "The service was both professional and affordable, exceeding my expectations. Right from the start, the contractor was transparent about the process, ensuring clarity in every step. They took the time to explain the issue in detail before beginning the work, making me feel confident in their expertise. Not only did they provide a clear breakdown of the repairs needed, but they also discussed potential solutions and costs upfront. There were no hidden fees or surprises, which I truly appreciated. Throughout the job, they maintained excellent communication, keeping me informed of the progress.The work was completed efficiently, with great attention to detail and professionalism. I highly recommend their services for anyone looking for reliable and transparent home repairs!",
  },
];

export const productsData = [
  {
    _id: 1,
    image: "/product_image_1.jpeg",
    userImage: "/user_image_1.jpeg",
    userType: "INFLUENCER",
    title: "Denim midi skirt with pockets",
    price: 23.0,
    rating: 4.5,
    location: "United States",
    tag: "Top seller",
    size: "UK 10/XL",
    offers: "open to offers",
  },
  {
    _id: 2,
    image: "/product_image_1.jpeg",
    userImage: "/user_image_1.jpeg",
    userType: "Eco-friendly store",
    title: "Denim midi skirt with pockets",
    price: 23.0,
    rating: 3.6,
    location: "United States",
    tag: "Top seller",
    size: "UK 10/XL",
    offers: "open to offers",
  },
  {
    _id: 3,
    image: "/product_image_1.jpeg",
    userImage: "/user_image_1.jpeg",
    userType: "Charity store",
    title: "Denim midi skirt with pockets",
    price: 23.0,
    rating: 4.5,
    location: "United States",
    tag: "Top seller",
    size: "UK 10/XL",
    offers: "open to offers",
  },
  {
    _id: 4,
    image: "/product_image_1.jpeg",
    userImage: "/user_image_1.jpeg",
    userType: "Ambassador",
    title: "Denim midi skirt with pockets",
    price: 23.0,
    rating: 4.5,
    location: "United States",
    tag: "Top seller",
    size: "UK 10/XL",
    offers: "open to offers",
  },
  {
    _id: 5,
    image: "/product_image_1.jpeg",
    userImage: "/user_image_1.jpeg",
    userType: "Eco-friendly store",
    title: "Denim midi skirt with pockets",
    price: 23.0,
    rating: 4.5,
    location: "United States",
    tag: "Top seller",
    size: "UK 10/XL",
    offers: "open to offers",
  },
  {
    _id: 6,
    image: "/product_image_1.jpeg",
    userImage: "/user_image_1.jpeg",
    userType: "INFLUENCER",
    title: "Denim midi skirt with pockets",
    price: 23.0,
    rating: 4.5,
    location: "United States",
    tag: "Top seller",
    size: "UK 10/XL",
    offers: "open to offers",
  },
  {
    _id: 7,
    image: "/product_image_1.jpeg",
    userImage: "/user_image_1.jpeg",
    userType: "Charity store",
    title: "Denim midi skirt with pockets",
    price: 23.0,
    rating: 4.5,
    location: "United States",
    tag: "Top seller",
    size: "UK 10/XL",
    offers: "open to offers",
  },
  {
    _id: 8,
    image: "/product_image_1.jpeg",
    userImage: "/user_image_1.jpeg",
    userType: "INFLUENCER",
    title: "Denim midi skirt with pockets",
    price: 23.0,
    rating: 4.5,
    location: "United States",
    tag: "Top seller",
    size: "UK 10/XL",
    offers: "open to offers",
  },
  {
    _id: 9,
    image: "/product_image_1.jpeg",
    userImage: "/user_image_1.jpeg",
    userType: "Ambassador",
    title: "Denim midi skirt with pockets",
    price: 23.0,
    rating: 4.5,
    location: "United States",
    tag: "Top seller",
    size: "UK 10/XL",
    offers: "open to offers",
  },
  {
    _id: 10,
    image: "/product_image_1.jpeg",
    userImage: "/user_image_1.jpeg",
    userType: "INFLUENCER",
    title: "Denim midi skirt with pockets",
    price: 23.0,
    rating: 4.5,
    location: "United States",
    tag: "Top seller",
    size: "UK 10/XL",
    offers: "open to offers",
  },
  {
    _id: 11,
    image: "/product_image_1.jpeg",
    userImage: "/user_image_1.jpeg",
    userType: "Charity store",
    title: "Denim midi skirt with pockets",
    price: 23.0,
    rating: 4.5,
    location: "United States",
    tag: "Top seller",
    size: "UK 10/XL",
    offers: "open to offers",
  },
  {
    _id: 12,
    image: "/product_image_1.jpeg",
    userImage: "/user_image_1.jpeg",
    userType: "Eco-friendly store",
    title: "Denim midi skirt with pockets",
    price: 23.0,
    rating: 4.5,
    location: "United States",
    tag: "Top seller",
    size: "UK 10/XL",
    offers: "open to offers",
  },
];
