export const productData = [
  {
    name: "Teens Top & Pant",
    image: "/offer_page_product3.png",
    price: 25,
    date: "24 Feb, 2024",
    color: "Red",
    size: "XLL",
    features: ["Authentication of Goods", "Buyer Protection"],
  },
  {
    name: "Teens Top & Pant",
    image: "/offer_page_product3.png",
    price: 24,
    date: "24 Feb, 2024",
    color: "Green",
    size: "XLL",
    features: ["Authentication of Goods", "Buyer Protection"],
  },
  {
    name: "Teens Top & Pant",
    image: "/offer_page_product3.png",
    price: 24,
    date: "24 Feb, 2024",
    color: "Blue",
    size: "XLL",
    features: ["Authentication of Goods", "Buyer Protection"],
  },
  {
    name: "Teens Top & Pant",
    image: "/offer_page_product3.png",
    price: 24,
    date: "24 Feb, 2024",
    color: "Blue",
    size: "XLL",
    features: ["Authentication of Goods", "Buyer Protection"],
  },
  {
    name: "Teens Top & Pant",
    image: "/offer_page_product3.png",
    price: 24,
    date: "24 Feb, 2024",
    color: "Blue",
    size: "XLL",
    features: ["Authentication of Goods", "Buyer Protection"],
  },
];
