import React from "react";
import AboutPageContainer from "./_components/AboutPageContainer";

export const metadata = {
  title: "About Us",
  description: "Generated by create next app",
};

const AboutUsPage = () => {
  return (
    <div>
      <AboutPageContainer></AboutPageContainer>
    </div>
  );
};

export default AboutUsPage;
